// Version: 1.05.00.45
/**
 * Standardized lists for validation and autocomplete.
 * Stores both Code and Name to allow flexibility in data entry.
 */

export type ReferenceItem = {
  code: string;
  name: string;
};

// --- VOLUME TYPES (Logistics Packaging) ---
export const VOLUME_TYPES_LIST: ReferenceItem[] = [
  { code: "Pallets", name: "Pallets / Paletes (PLT)" },
  { code: "Cartons", name: "Cartons / Caixas de Papelão (CTN)" },
  { code: "Wooden Crates", name: "Wooden Crates / Engradados (CRT)" },
  { code: "Wooden Cases", name: "Wooden Cases / Caixas de Madeira (CS)" },
  { code: "Drums", name: "Drums / Tambores (DRM)" },
  { code: "Bags", name: "Bags / Sacas (BAG)" },
  { code: "Rolls", name: "Rolls / Rolos (ROL)" },
  { code: "Bundles", name: "Bundles / Fardos (BDL)" },
  { code: "Bales", name: "Bales / Fardos Prensados (BLE)" },
  { code: "Skids", name: "Skids (SKD)" },
  { code: "Pieces", name: "Pieces / Peças Soltas (PCS)" },
  { code: "IBC", name: "IBC / Container Intermediário" },
  { code: "Totes", name: "Totes / Caixas Plásticas" },
  { code: "Reels", name: "Reels / Carretéis" },
];

// --- INCOTERMS 2020 ---
export const INCOTERMS_LIST: ReferenceItem[] = [
  { code: "EXW", name: "Ex Works" },
  { code: "FCA", name: "Free Carrier" },
  { code: "CPT", name: "Carriage Paid To" },
  { code: "CIP", name: "Carriage and Insurance Paid To" },
  { code: "DAP", name: "Delivered at Place" },
  { code: "DPU", name: "Delivered at Place Unloaded" },
  { code: "DDP", name: "Delivered Duty Paid" },
  { code: "FAS", name: "Free Alongside Ship" },
  { code: "FOB", name: "Free on Board" },
  { code: "CFR", name: "Cost and Freight" },
  { code: "CIF", name: "Cost, Insurance and Freight" },
];

// --- PAYMENT TERMS (Common) ---
export const PAYMENT_TERMS_LIST: ReferenceItem[] = [
  { code: "Imediato", name: "Immediate / Cash" },
  { code: "Antecipado", name: "Advance Payment" },
  { code: "Net 7", name: "Net 7 Days" },
  { code: "Net 10", name: "Net 10 Days" },
  { code: "Net 15", name: "Net 15 Days" },
  { code: "Net 30", name: "Net 30 Days" },
  { code: "Net 45", name: "Net 45 Days" },
  { code: "Net 60", name: "Net 60 Days" },
  { code: "Net 90", name: "Net 90 Days" },
  { code: "EOM", name: "End of Month" },
  { code: "COD", name: "Cash on Delivery" },
  { code: "LC", name: "Letter of Credit" },
  { code: "T/T", name: "Telegraphic Transfer" },
  { code: "50/50", name: "50% Advance / 50% Shipment" },
];

// --- CURRENCIES (ISO 4217) ---
export const CURRENCIES_LIST: ReferenceItem[] = [
  { code: "AFN", name: "Afghani" },
  { code: "EUR", name: "Euro" },
  { code: "ALL", name: "Lek" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "USD", name: "US Dollar" },
  { code: "AOA", name: "Kwanza" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "AZN", name: "Azerbaijan Manat" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "BDT", name: "Taka" },
  { code: "BBD", name: "Barbados Dollar" },
  { code: "BYN", name: "Belarusian Ruble" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "XOF", name: "CFA Franc BCEAO" },
  { code: "BMD", name: "Bermudian Dollar" },
  { code: "INR", name: "Indian Rupee" },
  { code: "BTN", name: "Ngultrum" },
  { code: "BOB", name: "Boliviano" },
  { code: "BOV", name: "Mvdol" },
  { code: "BAM", name: "Convertible Mark" },
  { code: "BWP", name: "Pula" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "BND", name: "Brunei Dollar" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "BIF", name: "Burundi Franc" },
  { code: "CVE", name: "Cabo Verde Escudo" },
  { code: "KHR", name: "Riel" },
  { code: "XAF", name: "CFA Franc BEAC" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "KYD", name: "Cayman Islands Dollar" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "CLF", name: "Unidad de Fomento" },
  { code: "CNY", name: "Yuan Renminbi" },
  { code: "COP", name: "Colombian Peso" },
  { code: "COU", name: "Unidad de Valor Real" },
  { code: "KMF", name: "Comorian Franc" },
  { code: "CDF", name: "Congolese Franc" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "CRC", name: "Costa Rican Colon" },
  { code: "HRK", name: "Kuna" },
  { code: "CUP", name: "Cuban Peso" },
  { code: "CUC", name: "Peso Convertible" },
  { code: "ANG", name: "Netherlands Antillean Guilder" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "DKK", name: "Danish Krone" },
  { code: "DJF", name: "Djibouti Franc" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "SVC", name: "El Salvador Colon" },
  { code: "ERN", name: "Nakfa" },
  { code: "SZL", name: "Lilangeni" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "FKP", name: "Falkland Islands Pound" },
  { code: "FJD", name: "Fiji Dollar" },
  { code: "XPF", name: "CFP Franc" },
  { code: "GMD", name: "Dalasi" },
  { code: "GEL", name: "Lari" },
  { code: "GHS", name: "Ghana Cedi" },
  { code: "GIP", name: "Gibraltar Pound" },
  { code: "GTQ", name: "Quetzal" },
  { code: "GBP", name: "Pound Sterling" },
  { code: "GNF", name: "Guinean Franc" },
  { code: "GYD", name: "Guyana Dollar" },
  { code: "HTG", name: "Gourde" },
  { code: "HNL", name: "Lempira" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "HUF", name: "Forint" },
  { code: "ISK", name: "Iceland Krona" },
  { code: "IDR", name: "Rupiah" },
  { code: "XDR", name: "SDR (Special Drawing Right)" },
  { code: "IRR", name: "Iranian Rial" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "ILS", name: "New Israeli Sheqel" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "JPY", name: "Yen" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "KZT", name: "Tenge" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "KPW", name: "North Korean Won" },
  { code: "KRW", name: "Won" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "KGS", name: "Som" },
  { code: "LAK", name: "Lao Kip" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "LSL", name: "Loti" },
  { code: "ZAR", name: "Rand" },
  { code: "LRD", name: "Liberian Dollar" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "MOP", name: "Pataca" },
  { code: "MGA", name: "Malagasy Ariary" },
  { code: "MWK", name: "Malawi Kwacha" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "MVR", name: "Rufiyaa" },
  { code: "MRU", name: "Ouguiya" },
  { code: "MUR", name: "Mauritius Rupee" },
  { code: "XUA", name: "ADB Unit of Account" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "MXV", name: "Mexican Unidad de Inversion (UDI)" },
  { code: "MDL", name: "Moldovan Leu" },
  { code: "MNT", name: "Tugrik" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "MZN", name: "Mozambique Metical" },
  { code: "MMK", name: "Kyat" },
  { code: "NAD", name: "Namibia Dollar" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "NIO", name: "Cordoba Oro" },
  { code: "NGN", name: "Naira" },
  { code: "MKD", name: "Denar" },
  { code: "OMR", name: "Rial Omani" },
  { code: "PKR", name: "Pakistan Rupee" },
  { code: "PAB", name: "Balboa" },
  { code: "PGK", name: "Kina" },
  { code: "PYG", name: "Guarani" },
  { code: "PEN", name: "Sol" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "PLN", name: "Zloty" },
  { code: "QAR", name: "Qatari Rial" },
  { code: "RON", name: "Romanian Leu" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "RWF", name: "Rwanda Franc" },
  { code: "SHP", name: "Saint Helena Pound" },
  { code: "WST", name: "Tala" },
  { code: "STN", name: "Dobra" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "SCR", name: "Seychelles Rupee" },
  { code: "SLL", name: "Leone" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "XSU", name: "Sucre" },
  { code: "SBD", name: "Solomon Islands Dollar" },
  { code: "SOS", name: "Somali Shilling" },
  { code: "SSP", name: "South Sudanese Pound" },
  { code: "LKR", name: "Sri Lanka Rupee" },
  { code: "SDG", name: "Sudanese Pound" },
  { code: "SRD", name: "Surinam Dollar" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "CHE", name: "WIR Euro" },
  { code: "CHW", name: "WIR Franc" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "TWD", name: "New Taiwan Dollar" },
  { code: "TJS", name: "Somoni" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "THB", name: "Baht" },
  { code: "TOP", name: "Pa’anga" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "TMT", name: "Turkmenistan New Manat" },
  { code: "UGX", name: "Uganda Shilling" },
  { code: "UAH", name: "Hryvnia" },
  { code: "AED", name: "UAE Dirham" },
  { code: "USN", name: "US Dollar (Next day)" },
  { code: "UYU", name: "Peso Uruguayo" },
  { code: "UYI", name: "Uruguay Peso en Unidades Indexadas (UI)" },
  { code: "UYW", name: "Unidad Previsional" },
  { code: "UZS", name: "Uzbekistan Sum" },
  { code: "VUV", name: "Vatu" },
  { code: "VES", name: "Bolívar Soberano" },
  { code: "VND", name: "Dong" },
  { code: "YER", name: "Yemeni Rial" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "ZWL", name: "Zimbabwe Dollar" },
];

// --- COUNTRIES (ISO 3166-1 alpha-3) ---
export const COUNTRIES_LIST: ReferenceItem[] = [
  { code: "ABW", name: "Aruba" },
  { code: "AFG", name: "Afghanistan" },
  { code: "AGO", name: "Angola" },
  { code: "AIA", name: "Anguilla" },
  { code: "ALA", name: "Åland Islands" },
  { code: "ALB", name: "Albania" },
  { code: "AND", name: "Andorra" },
  { code: "ARE", name: "United Arab Emirates" },
  { code: "ARG", name: "Argentina" },
  { code: "ARM", name: "Armenia" },
  { code: "ASM", name: "American Samoa" },
  { code: "ATA", name: "Antarctica" },
  { code: "ATF", name: "French Southern Territories" },
  { code: "ATG", name: "Antigua and Barbuda" },
  { code: "AUS", name: "Australia" },
  { code: "AUT", name: "Austria" },
  { code: "AZE", name: "Azerbaijan" },
  { code: "BDI", name: "Burundi" },
  { code: "BEL", name: "Belgium" },
  { code: "BEN", name: "Benin" },
  { code: "BES", name: "Bonaire, Sint Eustatius and Saba" },
  { code: "BFA", name: "Burkina Faso" },
  { code: "BGD", name: "Bangladesh" },
  { code: "BGR", name: "Bulgaria" },
  { code: "BHR", name: "Bahrain" },
  { code: "BHS", name: "Bahamas" },
  { code: "BIH", name: "Bosnia and Herzegovina" },
  { code: "BLM", name: "Saint Barthélemy" },
  { code: "BLR", name: "Belarus" },
  { code: "BLZ", name: "Belize" },
  { code: "BMU", name: "Bermuda" },
  { code: "BOL", name: "Bolivia" },
  { code: "BRA", name: "Brazil" },
  { code: "BRB", name: "Barbados" },
  { code: "BRN", name: "Brunei Darussalam" },
  { code: "BTN", name: "Bhutan" },
  { code: "BVT", name: "Bouvet Island" },
  { code: "BWA", name: "Botswana" },
  { code: "CAF", name: "Central African Republic" },
  { code: "CAN", name: "Canada" },
  { code: "CCK", name: "Cocos (Keeling) Islands" },
  { code: "CHE", name: "Switzerland" },
  { code: "CHL", name: "Chile" },
  { code: "CHN", name: "China" },
  { code: "CIV", name: "Côte d'Ivoire" },
  { code: "CMR", name: "Cameroon" },
  { code: "COD", name: "Congo, Democratic Republic of the" },
  { code: "COG", name: "Congo" },
  { code: "COK", name: "Cook Islands" },
  { code: "COL", name: "Colombia" },
  { code: "COM", name: "Comoros" },
  { code: "CPV", name: "Cabo Verde" },
  { code: "CRI", name: "Costa Rica" },
  { code: "CUB", name: "Cuba" },
  { code: "CUW", name: "Curaçao" },
  { code: "CXR", name: "Christmas Island" },
  { code: "CYM", name: "Cayman Islands" },
  { code: "CYP", name: "Cyprus" },
  { code: "CZE", name: "Czechia" },
  { code: "DEU", name: "Germany" },
  { code: "DJI", name: "Djibouti" },
  { code: "DMA", name: "Dominica" },
  { code: "DNK", name: "Denmark" },
  { code: "DOM", name: "Dominican Republic" },
  { code: "DZA", name: "Algeria" },
  { code: "ECU", name: "Ecuador" },
  { code: "EGY", name: "Egypt" },
  { code: "ERI", name: "Eritrea" },
  { code: "ESH", name: "Western Sahara" },
  { code: "ESP", name: "Spain" },
  { code: "EST", name: "Estonia" },
  { code: "ETH", name: "Ethiopia" },
  { code: "FIN", name: "Finland" },
  { code: "FJI", name: "Fiji" },
  { code: "FLK", name: "Falkland Islands (Malvinas)" },
  { code: "FRA", name: "France" },
  { code: "FRO", name: "Faroe Islands" },
  { code: "FSM", name: "Micronesia" },
  { code: "GAB", name: "Gabon" },
  { code: "GBR", name: "United Kingdom" },
  { code: "GEO", name: "Georgia" },
  { code: "GGY", name: "Guernsey" },
  { code: "GHA", name: "Ghana" },
  { code: "GIB", name: "Gibraltar" },
  { code: "GIN", name: "Guinea" },
  { code: "GLP", name: "Guadeloupe" },
  { code: "GMB", name: "Gambia" },
  { code: "GNB", name: "Guinea-Bissau" },
  { code: "GNQ", name: "Equatorial Guinea" },
  { code: "GRC", name: "Greece" },
  { code: "GRD", name: "Grenada" },
  { code: "GRL", name: "Greenland" },
  { code: "GTM", name: "Guatemala" },
  { code: "GUF", name: "French Guiana" },
  { code: "GUM", name: "Guam" },
  { code: "GUY", name: "Guyana" },
  { code: "HKG", name: "Hong Kong" },
  { code: "HMD", name: "Heard Island and McDonald Islands" },
  { code: "HND", name: "Honduras" },
  { code: "HRV", name: "Croatia" },
  { code: "HTI", name: "Haiti" },
  { code: "HUN", name: "Hungary" },
  { code: "IDN", name: "Indonesia" },
  { code: "IMN", name: "Isle of Man" },
  { code: "IND", name: "India" },
  { code: "IOT", name: "British Indian Ocean Territory" },
  { code: "IRL", name: "Ireland" },
  { code: "IRN", name: "Iran" },
  { code: "IRQ", name: "Iraq" },
  { code: "ISL", name: "Iceland" },
  { code: "ISR", name: "Israel" },
  { code: "ITA", name: "Italy" },
  { code: "JAM", name: "Jamaica" },
  { code: "JEY", name: "Jersey" },
  { code: "JOR", name: "Jordan" },
  { code: "JPN", name: "Japan" },
  { code: "KAZ", name: "Kazakhstan" },
  { code: "KEN", name: "Kenya" },
  { code: "KGZ", name: "Kyrgyzstan" },
  { code: "KHM", name: "Cambodia" },
  { code: "KIR", name: "Kiribati" },
  { code: "KNA", name: "Saint Kitts and Nevis" },
  { code: "KOR", name: "Korea, Republic of" },
  { code: "KWT", name: "Kuwait" },
  { code: "LAO", name: "Lao People's Democratic Republic" },
  { code: "LBN", name: "Lebanon" },
  { code: "LBR", name: "Liberia" },
  { code: "LBY", name: "Libya" },
  { code: "LCA", name: "Saint Lucia" },
  { code: "LIE", name: "Liechtenstein" },
  { code: "LKA", name: "Sri Lanka" },
  { code: "LSO", name: "Lesotho" },
  { code: "LTU", name: "Lithuania" },
  { code: "LUX", name: "Luxembourg" },
  { code: "LVA", name: "Latvia" },
  { code: "MAC", name: "Macao" },
  { code: "MAF", name: "Saint Martin (French part)" },
  { code: "MAR", name: "Morocco" },
  { code: "MCO", name: "Monaco" },
  { code: "MDA", name: "Moldova" },
  { code: "MDG", name: "Madagascar" },
  { code: "MDV", name: "Maldives" },
  { code: "MEX", name: "Mexico" },
  { code: "MHL", name: "Marshall Islands" },
  { code: "MKD", name: "North Macedonia" },
  { code: "MLI", name: "Mali" },
  { code: "MLT", name: "Malta" },
  { code: "MMR", name: "Myanmar" },
  { code: "MNE", name: "Montenegro" },
  { code: "MNG", name: "Mongolia" },
  { code: "MNP", name: "Northern Mariana Islands" },
  { code: "MOZ", name: "Mozambique" },
  { code: "MRT", name: "Mauritania" },
  { code: "MSR", name: "Montserrat" },
  { code: "MTQ", name: "Martinique" },
  { code: "MUS", name: "Mauritius" },
  { code: "MWI", name: "Malawi" },
  { code: "MYS", name: "Malaysia" },
  { code: "MYT", name: "Mayotte" },
  { code: "NAM", name: "Namibia" },
  { code: "NCL", name: "New Caledonia" },
  { code: "NER", name: "Niger" },
  { code: "NFK", name: "Norfolk Island" },
  { code: "NGA", name: "Nigeria" },
  { code: "NIC", name: "Nicaragua" },
  { code: "NIU", name: "Niue" },
  { code: "NLD", name: "Netherlands" },
  { code: "NOR", name: "Norway" },
  { code: "NPL", name: "Nepal" },
  { code: "NRU", name: "Nauru" },
  { code: "NZL", name: "New Zealand" },
  { code: "OMN", name: "Oman" },
  { code: "PAK", name: "Pakistan" },
  { code: "PAN", name: "Panama" },
  { code: "PCN", name: "Pitcairn" },
  { code: "PER", name: "Peru" },
  { code: "PHL", name: "Philippines" },
  { code: "PLW", name: "Palau" },
  { code: "PNG", name: "Papua New Guinea" },
  { code: "POL", name: "Poland" },
  { code: "PRI", name: "Puerto Rico" },
  { code: "PRK", name: "Korea, Democratic People's Republic of" },
  { code: "PRT", name: "Portugal" },
  { code: "PRY", name: "Paraguay" },
  { code: "PSE", name: "Palestine, State of" },
  { code: "PYF", name: "French Polynesia" },
  { code: "QAT", name: "Qatar" },
  { code: "REU", name: "Réunion" },
  { code: "ROU", name: "Romania" },
  { code: "RUS", name: "Russian Federation" },
  { code: "RWA", name: "Rwanda" },
  { code: "SAU", name: "Saudi Arabia" },
  { code: "SDN", name: "Sudan" },
  { code: "SEN", name: "Senegal" },
  { code: "SGP", name: "Singapore" },
  { code: "SGS", name: "South Georgia and the South Sandwich Islands" },
  { code: "SHN", name: "Saint Helena" },
  { code: "SJM", name: "Svalbard and Jan Mayen" },
  { code: "SLB", name: "Solomon Islands" },
  { code: "SLE", name: "Sierra Leone" },
  { code: "SLV", name: "El Salvador" },
  { code: "SMR", name: "San Marino" },
  { code: "SOM", name: "Somalia" },
  { code: "SPM", name: "Saint Pierre and Miquelon" },
  { code: "SRB", name: "Serbia" },
  { code: "SSD", name: "South Sudan" },
  { code: "STP", name: "Sao Tome and Principe" },
  { code: "SUR", name: "Suriname" },
  { code: "SVK", name: "Slovakia" },
  { code: "SVN", name: "Slovenia" },
  { code: "SWE", name: "Sweden" },
  { code: "SWZ", name: "Eswatini" },
  { code: "SXM", name: "Sint Maarten (Dutch part)" },
  { code: "SYC", name: "Seychelles" },
  { code: "SYR", name: "Syrian Arab Republic" },
  { code: "TCA", name: "Turks and Caicos Islands" },
  { code: "TCD", name: "Chad" },
  { code: "TGO", name: "Togo" },
  { code: "THA", name: "Thailand" },
  { code: "TJK", name: "Tajikistan" },
  { code: "TKL", name: "Tokelau" },
  { code: "TKM", name: "Turkmenistan" },
  { code: "TLS", name: "Timor-Leste" },
  { code: "TON", name: "Tonga" },
  { code: "TTO", name: "Trinidad and Tobago" },
  { code: "TUN", name: "Tunisia" },
  { code: "TUR", name: "Turkey" },
  { code: "TUV", name: "Tuvalu" },
  { code: "TWN", name: "Taiwan" },
  { code: "TZA", name: "Tanzania" },
  { code: "UGA", name: "Uganda" },
  { code: "UKR", name: "Ukraine" },
  { code: "UMI", name: "United States Minor Outlying Islands" },
  { code: "URY", name: "Uruguay" },
  { code: "USA", name: "United States" },
  { code: "UZB", name: "Uzbekistan" },
  { code: "VAT", name: "Holy See" },
  { code: "VCT", name: "Saint Vincent and the Grenadines" },
  { code: "VEN", name: "Venezuela" },
  { code: "VGB", name: "Virgin Islands, British" },
  { code: "VIR", name: "Virgin Islands, U.S." },
  { code: "VNM", name: "Viet Nam" },
  { code: "VUT", name: "Vanuatu" },
  { code: "WLF", name: "Wallis and Futuna" },
  { code: "WSM", name: "Samoa" },
  { code: "YEM", name: "Yemen" },
  { code: "ZAF", name: "South Africa" },
  { code: "ZMB", name: "Zambia" },
  { code: "ZWE", name: "Zimbabwe" },
];
