/**
 * Update Version Script
 *
 * This script serves as the Single Source of Truth bridge.
 * It parses the human-readable `docs/CHANGELOG.md` and generates the machine-readable `src/version.ts`.
 *
 * Flow:
 * 1. Read CHANGELOG.md
 * 2. Extract all versions using Regex
 * 3. Parse the bullet points for specific changes
 * 4. Write to src/version.ts (which App.tsx imports)
 */
/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require("fs");
const path = require("path");

const changelogPath = path.resolve(__dirname, "../docs/CHANGELOG.md");
const versionFilePath = path.resolve(__dirname, "../src/version.ts");

try {
  const changelogContent = fs.readFileSync(changelogPath, "utf-8");

  // Regex Strategy:
  // Matches headers like "## 1.05.00.38 - 2026-01-13" (No brackets)
  // Group 1: Version Number
  // Group 2: Date
  // The 'm' flag handles multi-line input, 'g' finds all matches.
  const versionRegex = /^## (.+?) - (.+?)$/gm;
  let match;
  const changes = [];

  while ((match = versionRegex.exec(changelogContent)) !== null) {
    const version = match[1];
    const date = match[2];

    // Extraction Logic:
    // We look for text strictly between this header (match.index) and the NEXT header.
    // If no next header exists, we go to the end of the file.
    const startIndex = match.index + match[0].length;
    let endIndex = changelogContent.indexOf("## ", startIndex);
    if (endIndex === -1) endIndex = changelogContent.length;

    const content = changelogContent.substring(startIndex, endIndex).trim();

    // Markdown Parsing:
    // 1. Split by newlines
    // 2. Filter only lines starting with "-" (bullet points)
    // 3. Clean up markdown syntax (**bold**, etc) for display
    const bulletPoints = content
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.startsWith("-"))
      .map((line) => line.replace(/^-\s*/, "").replace(/\*\*/g, ""));

    if (bulletPoints.length > 0) {
      changes.push({
        version,
        date,
        changes: bulletPoints,
      });
    }
  }

  // Get the latest version
  const latestVersion = changes.length > 0 ? changes[0].version : "0.0.0";

  // Generate version.ts content
  const fileContent = `// Auto-generated by scripts/update-version.js
// Do not edit manually. Source of truth is docs/CHANGELOG.md

export const APP_VERSION = "${latestVersion}";

export type ChangeLogItem = {
  version: string;
  date: string;
  changes: string[];
};

export const CHANGE_LOG: ChangeLogItem[] = ${JSON.stringify(changes, null, 2)};
`;

  fs.writeFileSync(versionFilePath, fileContent);
  console.log(
    `✅ Updated version.ts to v${latestVersion} with ${changes.length} changelog entries.`,
  );
} catch (error) {
  console.error("❌ Error updating version.ts:", error);
  process.exit(1);
}
